"""Recompute manuscript inferential families from archived CSVs, without DES/API.

Run normally to write followup_stats outputs; run with --check to recompute in
memory and verify every generated byte against the saved outputs without writing.
Archived Python files are hashed for provenance, never imported or executed.
"""
from pathlib import Path
from collections import defaultdict, Counter
import argparse
import csv
import hashlib
import io
import json
import platform
import zipfile
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'revision_work/analysis/followup_stats'
ZIP = ROOT / 'supplementary/paper7_reproducibility_package.zip'
BOOT = 10000
BOOT_SEED = 20260912
TRIGGER = 'results/llm_necessity_v2/necessity_v2_raw.csv'
MAIN1 = 'results/required_experiments/exp1_full_library_raw.csv'
MAIN2 = 'results/required_experiments/exp2_mission_semantics_raw.csv'
CROSS = 'results/crossed_mission_posterior/crossed_mission_posterior_raw.csv'
SOURCE_MEMBERS = [TRIGGER, MAIN1, MAIN2, CROSS,
                  'paper7_necessity_v2_experiment.py', 'paper7_statistical_tests.py']
TRIGGER_METHODS = [('Mission-blind', 'mission_blind_template'),
                   ('Semantic-sim', 'semantic_sim_posterior'),
                   ('Keyword', 'keyword_text_match'), ('LLM', 'llm_candidate_policy')]
TRIGGER_METRICS = [('branch_acc_triggered', 'Branch correctness'),
                   ('oracle_cov_triggered', 'Oracle coverage')]
COMPARISONS = [
    ('Guarded--Posterior argmin', MAIN1, None, 'llm_policy_guarded', 'posterior_argmin_mission_cost', 30),
    ('Guarded--Full library', MAIN1, None, 'llm_policy_guarded', 'verified_full_library_argmin', 30),
    ('Guarded--Rule-based', MAIN1, None, 'llm_policy_guarded', 'rule_based_fixed_cost', 30),
    ('Guarded--Top-1', MAIN2, None, 'full_mission_guarded', 'full_mission_top1', 30),
    ('Guarded--Mission-blind', MAIN2, None, 'full_mission_guarded', 'mission_blind_guarded', 30),
    ('LLM--Posterior-family top-2', CROSS, 'semantic_sensitive', 'llm_candidate_policy', 'posterior_family_top2', 12),
    ('LLM--Mission-blind broad', CROSS, 'semantic_sensitive', 'llm_candidate_policy', 'mission_blind_broad', 12),
]

def sha(data): return hashlib.sha256(data).hexdigest()
def finite(s):
    try: v = float(s)
    except (TypeError, ValueError): return None
    return v if np.isfinite(v) else None
def dump(value): return (json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + '\n').encode()
def csv_bytes(rows):
    stream = io.StringIO(newline='')
    writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
    writer.writeheader(); writer.writerows(rows)
    return stream.getvalue().encode()
def tex_p(p): return '$<0.0001$' if p < .0001 else f'{p:.4f}'
def signed_sums(d):
    d=np.asarray(d,dtype=float)
    assignments=np.arange(2**len(d),dtype=np.uint64)[:,None]
    signs=(((assignments >> np.arange(len(d),dtype=np.uint64)) & 1).astype(float)*2-1)
    return (signs*d).sum(1)
def exact_sign_flip(d):
    # Every full sign assignment is one pair of half assignments. Sorting the
    # right half permits exact tail counting without building 2^30 rows.
    n=len(d); observed=abs(float(np.sum(d))); tolerance=n*1e-14
    if observed <= tolerance: return 1.0
    left=signed_sums(d[:n//2]); right=np.sort(signed_sums(d[n//2:]))
    upper=len(right)-np.searchsorted(right,observed-tolerance-left,side='left')
    lower=np.searchsorted(right,-observed+tolerance-left,side='right')
    count=int(upper.sum())+int(lower.sum())
    assert 0<=count<=2**n
    p=count/2**n
    if n<=12:
        # Direct exhaustive cross-check of the meet-in-the-middle implementation.
        direct=float(np.mean(abs(signed_sums(d))>=observed-tolerance))
        assert p==direct
    return p
def infer(d):
    d = np.asarray(d, dtype=float)
    n = len(d)
    assert np.isfinite(d).all() and n in (12, 30)
    # Restarting the fixed RNG gives common paired mission draws within a family.
    rng = np.random.default_rng(BOOT_SEED)
    draws = rng.integers(0, n, size=(BOOT, n))
    ci = np.quantile(d[draws].mean(1), [.025, .975])
    p=exact_sign_flip(d)
    test,reps='exact_sign_flip_meet_in_middle',2**n
    return dict(n=n, delta=float(d.mean()), ci_low=float(ci[0]), ci_high=float(ci[1]),
                p_raw=float(p), sign_flip_method=test, sign_flip_assignments=reps)
def adjust(rows):
    order = np.argsort([r['p_raw'] for r in rows]); m = len(rows)
    running = 0.
    for rank, j in enumerate(order):
        running = max(running, min(1., (m-rank)*rows[j]['p_raw']))
        rows[j]['p_holm'] = float(running)
    running = 1.
    for rank in range(m-1, -1, -1):
        j = order[rank]
        running = min(running, rows[j]['p_raw']*m/(rank+1))
        rows[j]['p_bh'] = float(running)
    for row in rows: row['holm_significant_005'] = row['p_holm'] < .05

def main(check=False):
    with zipfile.ZipFile(ZIP) as z: members = {name:z.read(name) for name in SOURCE_MEMBERS}
    data = {name:list(csv.DictReader(io.StringIO(members[name].decode('utf-8-sig'))))
            for name in [TRIGGER, MAIN1, MAIN2, CROSS]}
    # Triggered outcomes: average finite paired seed means within each mission,
    # then give each mission equal weight. Zero-triggered metrics stay undefined.
    trows = data[TRIGGER]; keyed = {}
    for r in trows:
        key = (r['mission'], int(r['seed']), r['method'])
        assert key not in keyed
        keyed[key] = r
    missions = sorted({r['mission'] for r in trows}); seeds = sorted({int(r['seed']) for r in trows})
    assert len(missions) == 12 and seeds == list(range(10))
    omitted = []; means = {}; mission_rows = []; plot_rows = []
    for mission in missions:
        for seed in seeds:
            ref = keyed[(mission, seed, 'mission_blind_template')]
            ntr = float(ref['n_triggered'])
            for _, method in TRIGGER_METHODS:
                r = keyed[(mission, seed, method)]
                assert float(r['n_triggered']) == ntr and r['n_windows'] == ref['n_windows']
                for metric, _ in TRIGGER_METRICS:
                    assert (finite(r[metric]) is None) == (ntr == 0)
            if ntr == 0: omitted.append(dict(mission=mission, seed=seed, n_triggered=0))
        for label, method in TRIGGER_METHODS:
            for metric, metric_label in TRIGGER_METRICS:
                valid = [(s, finite(keyed[(mission,s,method)][metric])) for s in seeds]
                valid = [(s,v) for s,v in valid if v is not None]
                assert len(valid) in (9,10)
                value = float(np.mean([v for _,v in valid])); means[(mission,method,metric)] = value
                mission_rows.append(dict(mission=mission, method=method, metric=metric,
                                         included_seeds=';'.join(str(s) for s,_ in valid), n_seeds=len(valid), mean=value))
    assert len(omitted) == 2
    for label, method in TRIGGER_METHODS:
        for metric, metric_label in TRIGGER_METRICS:
            values = np.array([means[(m,method,metric)] for m in missions])
            ci = infer(values)
            plot_rows.append(dict(label=label, method=method, metric=metric, mean=float(values.mean()),
                                  ci_low=ci['ci_low'], ci_high=ci['ci_high'], n_missions=12))
    trigger_tests = []
    for label, method in TRIGGER_METHODS[1:]:
        for metric, metric_label in TRIGGER_METRICS:
            d = [means[(m,method,metric)]-means[(m,'mission_blind_template',metric)] for m in missions]
            trigger_tests.append(dict(family='triggered_six_tests', label=label, method=method,
                reference='mission_blind_template', metric=metric, metric_label=metric_label, **infer(d)))
    adjust(trigger_tests)
    fraction_by_mission = []
    for mission in missions:
        vals = [keyed[(mission,s,'mission_blind_template')] for s in seeds]
        fraction_by_mission.append(np.mean([float(r['n_triggered'])/float(r['n_windows']) for r in vals]))
    triggered_fraction = float(np.mean(fraction_by_mission))

    # Recompute the original decision-layer/crossed family from raw rows.
    # In crossed data, average archetypes within seed, then seeds within mission.
    pairwise = []; pair_missions = []; inclusion = []
    for label, filename, scope, ma, mb, expected_n in COMPARISONS:
        sub = [r for r in data[filename] if (scope is None or r['scope']==scope) and r['method'] in (ma,mb)]
        cells = defaultdict(list); unique_keys=set()
        for r in sub:
            key = (r['mission'], int(r['seed']), r.get('archetype',''), r['method'])
            assert key not in unique_keys; unique_keys.add(key)
            cells[(r['mission'],int(r['seed']),r['method'])].append(r)
        mids = sorted({r['mission'] for r in sub}); assert len(mids)==expected_n
        # Pair the same seeds and, where applicable, the same archetypes.
        for m in mids:
            for s in range(10):
                a = cells[(m,s,ma)]; b = cells[(m,s,mb)]
                assert len(a)==len(b)==(5 if scope else 1)
                assert sorted(r.get('archetype','') for r in a)==sorted(r.get('archetype','') for r in b)
        for metric, metric_label in [('mean_regret','Regret'),('invalid_action_rate','Invalidity')]:
            method_means={}
            for m in mids:
                for method in (ma,mb):
                    seed_means=[]
                    for seed in range(10):
                        values=[finite(r[metric]) for r in cells[(m,seed,method)]]
                        assert all(v is not None for v in values)
                        seed_means.append(np.mean(values))
                    method_means[(m,method)]=float(np.mean(seed_means))
            d=[method_means[(m,ma)]-method_means[(m,mb)] for m in mids]
            result=dict(family='main_crossed_fourteen_tests',comparison=label,source=filename,
                        scope=scope or 'all',method_a=ma,method_b=mb,metric=metric,metric_label=metric_label,
                        mean_a=float(np.mean([method_means[(m,ma)] for m in mids])),
                        mean_b=float(np.mean([method_means[(m,mb)] for m in mids])),**infer(d))
            pairwise.append(result)
            pair_missions.extend(dict(comparison=label,metric=metric,mission=m,mean_a=method_means[(m,ma)],
                                      mean_b=method_means[(m,mb)],delta=v) for m,v in zip(mids,d))
        inclusion.append(dict(comparison=label,n_missions=len(mids),seeds_per_mission=10,
                              rows_per_seed_method=5 if scope else 1,
                              archetypes=sorted({r.get('archetype','') for r in sub}) if scope else []))
    assert len(pairwise)==14; adjust(pairwise)
    assert abs(pairwise[0]['mean_a']-.4863962962962962)<1e-12
    # Independent arithmetic cross-check for all equal-cell-size mission means.
    for r in pairwise:
        original=data[r['source']]
        for method, key in [(r['method_a'],'mean_a'),(r['method_b'],'mean_b')]:
            values=[float(x[r['metric']]) for x in original if x['method']==method and
                    (r['scope']=='all' or x['scope']==r['scope'])]
            assert abs(float(np.mean(values))-r[key])<1e-12

    # TeX replacements include complete subsection boundaries but no following subsection.
    tp={(r['method'],r['metric']):r for r in trigger_tests}
    pm={(r['method'],r['metric']):r['mean'] for r in plot_rows}
    llm_b=tp[('llm_candidate_policy','branch_acc_triggered')]
    key_b=tp[('keyword_text_match','branch_acc_triggered')]
    llm_c=tp[('llm_candidate_policy','oracle_cov_triggered')]
    def ci_tex(r): return f"[$ {r['ci_low']:+.4f}, {r['ci_high']:+.4f} $]"
    trigger_lines=[r'\begin{revision}',r'\subsection{Where Mission Conditioning Changes the Action}',
        r'\label{subsec:triggered-branch}',
        r'The aggregate results include windows in which mission priorities do not change the oracle action. We therefore examine \emph{condition-triggered} windows, where the mission oracle differs from a neutral oracle using balanced costs and no guards. The twelve challenge missions use development vocabulary to test conditional mission decisions; the held-out wording experiment in Section~\ref{subsec:ood-mission-semantics} tests a separate semantic question. On triggered windows, oracle coverage measures whether the candidate set contains the mission oracle, and branch correctness measures whether the selected action matches it. The TF-IDF word/character $n$-gram matcher, Semantic-sim, supplies a lexical similarity control.',
        '',
        f'Triggered windows constitute {100*triggered_fraction:.1f}\\% of sampled windows. For both plotted metrics, we first average the finite seed-level conditional scores within a mission and then weight the twelve mission means equally. Two of the 120 mission--seed cells have no triggered windows; their undefined conditional scores are omitted for every generator. The affected missions contribute nine seed scores each, and the other ten missions contribute ten. All twelve missions remain in the comparison.',
        r'\end{revision}', '', r'\begin{figure}[pos=!htbp]',r'\revisionfloatcolor',r'\centering',r'\begin{tikzpicture}',
        r'\begin{axis}[ybar,bar width=7pt,width=\linewidth,height=5.0cm,ymin=0,ymax=1.0,',
        r'ylabel={Triggered-window score},symbolic x coords={Mission-blind,Semantic-sim,Keyword,LLM},',
        r'xtick=data,x tick label style={font=\small},legend style={at={(0.5,1.02)},anchor=south,legend columns=2,font=\small,draw=none},',
        r'ymajorgrids,major grid style={dotted,gray!40},enlarge x limits=0.20]']
    for metric,_ in TRIGGER_METRICS:
        coords=' '.join(f'({label},{pm[(method,metric)]:.4f})' for label,method in TRIGGER_METHODS)
        trigger_lines.append(r'\addplot coordinates {'+coords+'};')
    trigger_lines += [r'\legend{Branch correctness,Oracle coverage}',r'\end{axis}',r'\end{tikzpicture}',
        r'\caption{Condition-triggered performance, with seeds averaged within mission and all twelve missions weighted equally. All generators share the verifier and posterior-cost selector. Paired mission-level inference is reported in Table~\ref{tab:triggered-tests}.}',
        r'\label{fig:triggered-branch}',r'\end{figure}', '',r'\begin{revision}',
        f"Mission-conditioned LLM candidates increase branch correctness by {llm_b['delta']:.4f} over the mission-blind template (95\\% CI {ci_tex(llm_b)}, Holm-adjusted $p={llm_b['p_holm']:.4f}$); the keyword parser's difference is {key_b['delta']:.4f} (CI {ci_tex(key_b)}, adjusted $p={key_b['p_holm']:.4f}$). The LLM oracle-coverage difference is {llm_c['delta']:.4f}, but its interval includes zero (CI {ci_tex(llm_c)}, adjusted $p={llm_c['p_holm']:.4f}$). Thus this slice supports a change in the selected branch, while the coverage difference is not statistically resolved across these twelve missions.",
        '',
        r'Table~\ref{tab:triggered-tests} covers the complete six-test family: three generators versus the mission-blind reference on each of the two plotted outcomes. Confidence intervals use 10,000 mission bootstrap resamples; the paired sign-flip test enumerates all $2^{12}=4096$ sign assignments. Holm adjustment controls the family-wise error rate, and Benjamini--Hochberg (BH) values are included for comparison. The intervals are pointwise rather than simultaneous.',
        r'\end{revision}', '',r'\begin{table}[pos=!htbp]',r'\revisionfloatcolor',r'\centering',
        r'\caption{Triggered-window paired inference over twelve mission means. Differences are the named generator minus mission-blind. Adjustments cover all six rows.}',
        r'\label{tab:triggered-tests}',r'\scriptsize',r'\setlength{\tabcolsep}{3pt}',
        r'\begin{tabular}{llrlrr}',r'\toprule',r'Generator & Metric & Difference & 95\% CI & $p_{\rm Holm}$ & $p_{\rm BH}$ \\',r'\midrule']
    for r in trigger_tests:
        trigger_lines.append(f"{r['label']} & {r['metric_label']} & ${r['delta']:+.4f}$ & {ci_tex(r)} & {tex_p(r['p_holm'])} & {tex_p(r['p_bh'])} \\\\")
    trigger_lines += [r'\bottomrule',r'\end{tabular}',r'\end{table}', '',r'\begin{revision}',
        r'The keyword parser also improves branch correctness on this familiar vocabulary. The finding supports the use of mission context in candidate construction, with benefits available to both keyword and language-model interfaces. It complements the held-out semantic comparison and the strong aggregate results of broad or exhaustive candidate exposure.',r'\end{revision}','']

    pair_lines=[r'\begin{revision}',r'\subsection{Statistical Significance of Pairwise Comparisons}',r'\label{subsec:significance}',
        r'Table~\ref{tab:significance} reports the complete decision-layer and crossed comparison family: seven comparisons on regret and invalidity, giving fourteen tests. Each method first averages its ten seed values within a mission. In the crossed semantic-sensitive subset, the five represented posterior archetypes are averaged within each seed before the seed means are averaged. Methods are paired on the same mission, seed, and archetype cells, and each mission receives equal weight.',
        '',
        r'Pointwise 95\% confidence intervals use 10,000 mission bootstrap resamples. Two-sided paired sign-flip probabilities are exact: all $2^n$ assignments are counted, using two half-sample enumerations for the thirty-mission comparisons. Both Holm and Benjamini--Hochberg (BH) adjustments cover all fourteen tests in this table; inferential statements use Holm at 0.05.',
        '',
        r'The held-out wording family in Table~\ref{tab:ood-cluster-tests} addresses semantic generalization; the triggered family in Table~\ref{tab:triggered-tests} addresses conditional branch selection; the present family addresses decision-layer trade-offs. Multiplicity control is scoped to each of these scientific questions. Other reported contrasts are descriptive unless accompanied by their stated paired inference. Resampling characterizes variation across the evaluated missions with the archived diagnostic pool held fixed.',
        r'\end{revision}','',r'\begin{table}[pos=!htbp]',r'\revisionfloatcolor',r'\centering',
        r'\caption{Mission-level paired inference for the fourteen-test decision-layer/crossed family. Differences are the first method minus the reference; negative regret or invalidity is lower. $n=12$ denotes crossed semantic-sensitive comparisons. Intervals are pointwise.}',
        r'\label{tab:significance}',r'\scriptsize',r'\setlength{\tabcolsep}{3pt}',
        r'\begin{tabular}{llrrlrr}',r'\toprule',
        r'Comparison & Metric & $n$ & Difference & 95\% CI & $p_{\rm Holm}$ & $p_{\rm BH}$ \\',r'\midrule']
    for r in pairwise:
        comparison_tex=r['comparison'].replace('--',r' $-$ ')
        pair_lines.append(f"{comparison_tex} & {r['metric_label']} & {r['n']} & ${r['delta']:+.4f}$ & {ci_tex(r)} & {tex_p(r['p_holm'])} & {tex_p(r['p_bh'])} \\\\")
    pair_lines += [r'\bottomrule',r'\end{tabular}',r'\end{table}','',r'\begin{revision}',
        r'Guarded selection reduces both regret and invalidity relative to direct top-candidate deployment. Relative to posterior argmin and fixed rules, it reduces invalidity; its regret is higher than both posterior argmin and verified full-library selection. The guarded and mission-blind policies do not separate on aggregate regret or invalidity after Holm adjustment. In the crossed subset, the LLM candidate rule improves both outcomes over the compact posterior-family top-2 rule, while its regret is higher than the broad mission-blind template. These comparisons support the contributions of ranking and guard enforcement while retaining the advantages of broad candidate exposure.',r'\end{revision}','']
    # Ensure interpretation matches recalculated significance, not old table flags.
    significant={ (r['comparison'],r['metric']):r['p_holm']<.05 for r in pairwise }
    assert significant[('Guarded--Top-1','mean_regret')] and significant[('Guarded--Top-1','invalid_action_rate')]
    assert not significant[('Guarded--Mission-blind','mean_regret')]
    assert not significant[('Guarded--Mission-blind','invalid_action_rate')]
    assert significant[('LLM--Posterior-family top-2','mean_regret')]
    assert significant[('LLM--Posterior-family top-2','invalid_action_rate')]
    assert significant[('LLM--Mission-blind broad','mean_regret')]

    artifacts={
        'triggered_plot_means.csv':csv_bytes(plot_rows),
        'triggered_mission_means.csv':csv_bytes(mission_rows),
        'triggered_tests.csv':csv_bytes(trigger_tests),
        'pairwise_tests.csv':csv_bytes(pairwise),
        'pairwise_mission_means.csv':csv_bytes(pair_missions),
        'triggered_section.tex':('\n'.join(trigger_lines)).encode(),
        'pairwise_section.tex':('\n'.join(pair_lines)).encode(),
    }
    provenance=dict(source_zip='supplementary/paper7_reproducibility_package.zip',source_zip_sha256=sha(ZIP.read_bytes()),
        members={name:dict(bytes=len(content),sha256=sha(content)) for name,content in members.items()},
        script_sha256=sha(Path(__file__).read_bytes()),runtime=dict(python=platform.python_version(),numpy=np.__version__),
        settings=dict(bootstrap_resamples=BOOT,bootstrap_seed=BOOT_SEED,bootstrap_rng_reset_per_test=True,
                      thirty_mission_sign_flips='all 2^30, counted exactly via sorted half-assignment sums',
                      twelve_mission_sign_flips='all 4096',
                      pointwise_percentile_ci=True,sign_flip_mean_tolerance=1e-14),
        triggered=dict(missions=12,seeds_per_mission=10,omitted_zero_triggered_cells=omitted,
                       finite_pairs=118,fraction_of_all_windows=triggered_fraction,
                       weighting='Equal finite seed metrics within mission, then equal mission means; zero-triggered metrics omitted, not zero-imputed.',
                       comparison_family='All three non-reference plotted generators versus mission-blind on both plotted metrics; six tests.'),
        main_crossed=dict(comparison_family='Existing seven comparisons times regret/invalidity; fourteen tests.',inclusion=inclusion,
                          crossed_weighting='Five observed semantic-sensitive archetypes within seed, ten seeds within mission, missions equally weighted.',
                          crossed_unrepresented_archetype='ble_rid_dominant has no semantic_sensitive rows and is not imputed.'),
        interpretation='Separate scientific families control their own multiplicity. Pointwise intervals are not simultaneous coverage and family corrections are not manuscript-wide FWER.',
        input_code_execution='None: archive scripts only hashed, no DES, API, fitting, or archived code execution.',
        checks=dict(unique_rows=True,paired_seed_archetype_cells=True,zero_triggered_symmetric_missingness=True,
                    complete_mission_counts=True,raw_mean_arithmetic_crosscheck=True,text_matches_significance=True,
                    exact_sign_flip_twelve_mission_direct_enumeration_crosscheck=True),
        generated_artifacts={name:dict(bytes=len(value),sha256=sha(value)) for name,value in artifacts.items()})
    artifacts['provenance_and_checks.json']=dump(provenance)
    readme=f'''# Follow-up statistical repair

Run `python revision_work/reviewer_followup_stats.py` from the package root to regenerate these derived outputs. Run the same command with `--check` to recompute in memory and compare every output byte without writing. Only archived CSV inputs are read; archived Python is never executed. Source hashes, software versions, inclusion, weighting, tests, and output hashes are in `provenance_and_checks.json`.

Use `triggered_section.tex` and `pairwise_section.tex` as numerical companions when checking the canonical manuscript. Do not replace entire sections with these generated fragments: the canonical source contains subsequent caption, wording and layout refinements, including the Figure 6 adjusted p-values. Transfer only verified numerical changes while preserving those refinements and labels, then rebuild and refresh response locations.

The 12-mission triggered plot now uses equal mission weighting for all 8 bars. Two zero-triggered seed cells have undefined conditional metrics and are omitted symmetrically, so two missions have 9 usable seeds and ten have 10. Means therefore differ slightly from the old 118-pair averages. The inferential family includes all six generator/outcome contrasts shown by that plot. LLM branch improvement survives Holm; LLM coverage improvement does not. The main/crossed 14-test family is independently reconstructed from raw seed/archetype CSVs, with Holm and BH columns. All sign-flip probabilities are exact. A meet-in-the-middle method counts all 2^30 assignments using two arrays of 2^15 half-sample sums; for twelve missions, the algorithm is cross-checked against direct enumeration of all 4,096 assignments. All intervals are pointwise 95% intervals over {BOOT:,} mission bootstrap samples.

These are scientifically scoped comparison families, not a global manuscript-wide FWER claim. Sign-flip inference assumes the paired mission differences are sign-exchangeable under the null. The fixed authored missions and archived fitted diagnostic pool limit generalization; resampling does not create new language generations or independent network deployments.
'''
    artifacts['README.md']=readme.encode()
    if check:
        for name,content in artifacts.items():
            recorded = (OUT/name).read_bytes()
            if name == 'provenance_and_checks.json':
                saved_metadata = json.loads(recorded)
                current_metadata = json.loads(content)
                saved_metadata.pop('runtime')
                current_metadata.pop('runtime')
                assert saved_metadata == current_metadata, f'Output mismatch: {name}'
            else:
                assert recorded == content, f'Output mismatch: {name}'
        print(f'PASS: {len(artifacts)} outputs recomputed identically apart from recorded runtime metadata; no files written. Current Python {platform.python_version()}, NumPy {np.__version__}.')
    else:
        OUT.mkdir(parents=True,exist_ok=True)
        for name,content in artifacts.items(): (OUT/name).write_bytes(content)
        print(json.dumps(dict(output=str(OUT),triggered_fraction=triggered_fraction,
                              trigger_tests=trigger_tests,pairwise_tests=pairwise),indent=2))

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true')
    main(parser.parse_args().check)
